<center><h2><span style="color:green"> Importing numpy </style></h2></center>

In [1]:
import numpy as np

<center><h2><span style="color:yellow"> Two 3x3 matrices with random values and their sum </style></h2></center>

In [2]:
a = np.random.rand(3, 3)
b = np.random.rand(3, 3)
c = a + b
print(c)

[[0.8957329  0.67310677 1.54515666]
 [0.49676046 1.74654297 1.33175663]
 [0.68992753 1.1214425  0.99253808]]


<center><h2><span style="color:red"> Two 3x3 matrices with random values and their product </style></h2></center>

In [3]:
a = np.random.rand(3, 3)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = a * b
print(c)

[[0.25876487 0.81950693 1.43569625]
 [1.62145659 0.59098628 3.76129196]
 [6.19013456 1.36705148 4.18057055]]


<center><h2><span style="color:purple"> A unit matrix </style></h2></center>

In [4]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<center><h2><span style="color:cyan"> A three dimensional matrix </style></h2></center>

In [5]:
a = np.random.rand(3, 3, 3)
print(a)

[[[0.36957224 0.56030547 0.09343406]
  [0.75938943 0.87178584 0.11832932]
  [0.04851547 0.27465251 0.19108876]]

 [[0.30332841 0.2092037  0.28757161]
  [0.37256554 0.67575874 0.99975247]
  [0.0737777  0.51655596 0.01639751]]

 [[0.61339969 0.03997524 0.09836143]
  [0.90424986 0.08688942 0.20181364]
  [0.36707691 0.89471755 0.51564936]]]


<center><h2><span style="color:orange"> An array from 1 to 100 with step 4 </style></h2></center>

In [6]:
a = np.arange(1, 100, 4)
print(a)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


<center><h2><span style="color:teal"> Two arrays and finding the index of the common elements </style></h2></center>

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 7, 3, 9, 10])
c = np.where(np.in1d(a, b))
print([i for i in c[0]])  

[0, 2]


<center><h2><span style="color:violet"> An array with 10 values from 50 to 150 using linspace </style></h2></center>

In [8]:
a = np.linspace(50, 150, 10)
print(a)

[ 50.          61.11111111  72.22222222  83.33333333  94.44444444
 105.55555556 116.66666667 127.77777778 138.88888889 150.        ]


<center><h2><span style="color:coral"> A 6x4 matrix with the same value in each row </style></h2></center>

In [9]:
a = np.full((6, 4), 5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
